[package]

name = "cpal"
version = "0.2.1"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
description = "Cross-platform audio playing library in pure Rust."
repository = "https://github.com/tomaka/cpal"
documentation = "http://tomaka.github.io/cpal/"
license = "Apache-2.0"
keywords = ["audio", "sound"]

[dependencies]
libc = "*"
lazy_static = "0.1"
winapi = "0.2.3"
ole32-sys = "0.1"

[target.i686-unknown-linux-gnu.dependencies.alsa-sys]
version = "0"
path = "alsa-sys"

[target.x86_64-unknown-linux-gnu.dependencies.alsa-sys]
version = "0"
path = "alsa-sys"

[target.x86_64-apple-darwin.dependencies]
coreaudio-rs = "*"

[dev-dependencies]
vorbis = "0"
