[package]

name = "cpal"
version = "0.0.1"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
description = "Cross-platform audio playing library in pure Rust."
keywords = ["audio", "sound"]

[target.i686-pc-windows-gnu.dependencies.winapi]
git = "https://github.com/tomaka/winapi-rs"
branch = "mmdeviceapi"
features = ["ole32"]

[target.x86_64-pc-windows-gnu.dependencies.winapi]
git = "https://github.com/tomaka/winapi-rs"
branch = "mmdeviceapi"
features = ["ole32"]

[dev-dependencies.vorbis]
git = "https://github.com/tomaka/vorbis-rs"
