[package]
name = "cpal"
version = "0.3.0"
authors = ["The CPAL contributors", "Pierre Krieger <pierre.krieger1708@gmail.com>"]
description = "Low-level cross-platform audio playing library in pure Rust."
repository = "https://github.com/tomaka/cpal"
documentation = "http://tomaka.github.io/cpal/"
license = "Apache-2.0"
keywords = ["audio", "sound"]

[dependencies]
futures = "0.1.0"
libc = "0.2"
lazy_static = "0.2"
winapi = "0.2.8"
ole32-sys = "0.2"
kernel32-sys = "0.2"

[target.arm-unknown-linux-gnueabihf.dependencies.alsa-sys]
version = "0.1"
path = "alsa-sys"

[target.mipsel-unknown-linux-gnu.dependencies.alsa-sys]
version = "0.1"
path = "alsa-sys"

[target.i686-unknown-linux-gnu.dependencies.alsa-sys]
version = "0.1"
path = "alsa-sys"

[target.x86_64-unknown-linux-gnu.dependencies.alsa-sys]
version = "0.1"
path = "alsa-sys"

[target.x86_64-apple-darwin.dependencies]
coreaudio-rs = "0.6"
