[package]

name = "cpal"
version = "0.0.8-pre"
authors = ["Pierre Krieger <pierre.krieger1708@gmail.com>"]
description = "Cross-platform audio playing library in pure Rust."
repository = "https://github.com/tomaka/cpal"
documentation = "http://tomaka.github.io/cpal/"
license = "Apache-2.0"
keywords = ["audio", "sound"]

[target.i686-pc-windows-gnu.dependencies.winapi]
version = "0"
features = ["ole32"]

[target.x86_64-pc-windows-gnu.dependencies.winapi]
version = "0"
features = ["ole32"]

[target.i686-unknown-linux-gnu.dependencies.alsa-sys]
version = "^0.0.1"
path = "alsa-sys"

[target.x86_64-unknown-linux-gnu.dependencies.alsa-sys]
version = "^0.0.1"
path = "alsa-sys"

[dev-dependencies]
vorbis = "0"
